services:
  - type: web
    name: sistema-horarios-ficct
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
    numInstances: 1

databases:
  - name: ficct-db
    plan: free
    databaseName: ficct
    user: ficct_user