services:
  - type: web
    name: ficcthorarios
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    numInstances: 1

databases:
  - name: ficct-db
    plan: free